nomina2/Controllers/PaymentController.cs
using nomina2.Models.DAO;
using nomina2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace nomina9.Controllers
{
    public class PaymentController : Controller
    {
        private PaymentDAO paymentRepository = new PaymentDAO();
        private UserDAO userRepostiory = new UserDAO();




        // GET: Payment
        public ActionResult ListPayment(string searchKeyword)
        {
            ViewBag.SearchKeyword = searchKeyword; // Guarda el valor en ViewBag

            // Obtén la lista de pagos y la lista de usuarios
            List<PaymentDTO> payments = paymentRepository.ReadPayments(searchKeyword);
            List<UserDTO> users = userRepostiory.ReadUsers3(searchKeyword); // Cambia "userRepostiory" al nombre correcto de tu repositorio de usuarios

            // Crea un modelo compuesto que incluya tanto la lista de pagos como la lista de usuarios
            var model = new Tuple<List<PaymentDTO>, List<UserDTO>>(payments, users);

            // Devuelve la vista con el modelo compuesto
            return View(model);
        }


        public ActionResult CreatePayment(int userId, decimal amountSalary, decimal department)
        {
            ViewBag.UserId = userId; // Pasar el ID de usuario a la vista
            ViewBag.AmountSalary = amountSalary; // Pasar el AmountSalary a la vista
            ViewBag.Department_id = department; // Pasar el AmountSalary a la vista

            return View();
        }



        // POST: User/Create
        [HttpPost]
        public ActionResult CreatePayment(PaymentDTO payment)
        {
            try
            {
                string result = paymentRepository.InsertPayment(payment);

                if (result == "Success")
                {
                    int Id_actual = payment.Id_user;

                    // Redireccionar a la vista "ListPayment" con el UserId como valor de búsqueda
                    return RedirectToAction("ListPayment", new { searchKeyword = Id_actual });
                }
                else
                {
                    // Si la inserción falla, agregar un mensaje de alerta a la ViewBag
                    ViewBag.ErrorMessage = "Error al insertar el overtime en la base de datos.";
                }
            }
            catch (Exception ex)
            {
                // En caso de excepción, agregar un mensaje de alerta a la ViewBag
                ViewBag.ErrorMessage = "Ocurrió un error durante la inserción del overtime: " + ex.Message;
            }

            // Devolver la vista "Createpayment" con los datos del overtime ingresados previamente y el mensaje de alerta (si corresponde).
            return View(payment);
        }


        // GET: Payment/EditPayment/5
        public ActionResult EditPayment(int id, int userId, decimal amountSalary, decimal department)
        {
            ViewBag.UserId = userId; // Pasar el ID de usuario a la vista
            ViewBag.AmountSalary = amountSalary; // Pasar el AmountSalary a la vista
            ViewBag.Department_id = department; // Pasar el AmountSalary a la vista
            try
            {
                // Obtén el pago específico utilizando el método GetPaymentById del repositorio PaymentDAO
                PaymentDTO payment = paymentRepository.GetPaymentById(id);
                if (payment != null)
                {
                    // Muestra la vista de edición con los detalles del pago
                    return View(payment);
                }
                else
                {
                    Console.WriteLine("Payment not found");
                    return RedirectToAction("ListPayment");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting payment: " + ex.Message);
                return RedirectToAction("ListPayment");
            }
        }

        // POST: Payment/EditPayment/5
        [HttpPost]
        public ActionResult EditPayment(PaymentDTO payment)
        {
            try
            {
                string result = paymentRepository.UpdatePayment(payment);
                Console.WriteLine("Payment updated: " + result);

                int Id_actual = payment.Id_user;

                // Redireccionar a la vista "ListPayment" con el UserId como valor de búsqueda
                return RedirectToAction("ListPayment", new { searchKeyword = Id_actual });
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error updating payment: " + ex.Message);
                return View(payment);
            }
        }

        public ActionResult DeletePayment(int id, int userId)
        {
            ViewBag.UserId = userId; // Pasar el ID de usuario a la vista
            try
            {
                string result = paymentRepository.DeletePayment(id);
                Console.WriteLine("Payment deleted: " + result);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error deleting payment: " + ex.Message);
            }

            // Redireccionar a la vista "ListPayment" después de eliminar el pago
            int Id_actual = userId;

            // Redireccionar a la vista "ListPayment" con el UserId como valor de búsqueda
            return RedirectToAction("ListPayment", new { searchKeyword = Id_actual });
            //return RedirectToAction("ListPayment");
        }







    }
}

nomina2/Controllers/UserController.cs
using nomina2.Models;
using nomina2.Models.DAO;
using nomina2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nomina2.Controllers
{
    public class UserController : Controller
    {
        private UserDAO userRepository = new UserDAO();
        private readonly OvertimeDAO overtimeRepository = new OvertimeDAO();
        private readonly DeductionDAO deductionRepository = new DeductionDAO();
        //private readonly LicenseDAO licenseRepository = new LicenseDAO();

        // GET: User
        public ActionResult ListUser(string searchKeyword)
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadUsers(searchKeyword));
        }

        public ActionResult ListUserSecurity(string searchKeyword)
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadUsers(searchKeyword));
        }




        public ActionResult RolesList()
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadRoles());
        }

        public ActionResult ListDepartament()
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadDepartament());
        }

        public ActionResult CreateUser()
        {
            // Obtener los roles disponibles
            var roles = userRepository.ReadRoles().ToList();
            var departaments = userRepository.ReadDepartament().ToList();
            ViewBag.Roles = new SelectList(roles, "id", "Description");
            ViewBag.Departaments = new SelectList(departaments, "id_departament", "Description");

            return View();
        }


        [HttpPost]
        public ActionResult CreateUser(UserDTO user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (user.Password == user.ConfirmPassword)
                    {
                        string result = userRepository.InsertUser(user);

                        if (result == "Success")
                        {
                            // Redireccionar a la vista "Index" en caso de éxito
                            return RedirectToAction("Login");
                        }
                        else
                        {
                            // Si la inserción falla, agregar un mensaje de alerta a la ViewBag
                            ViewBag.ErrorMessage = "Error al insertar el usuario en la base de datos.";
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("ConfirmPassword", "Passwords do not match");
                    }
                }

                // Si la validación falla, recuperar las listas de roles y departamentos
                var roles = userRepository.ReadRoles().ToList();
                var departaments = userRepository.ReadDepartament().ToList();
                ViewBag.Roles = new SelectList(roles, "id", "Description");
                ViewBag.Departaments = new SelectList(departaments, "id_departament", "Description");

                return View(user);
            }
            catch (Exception ex)
            {
                // En caso de excepción, agregar un mensaje de alerta a la ViewBag
                ViewBag.ErrorMessage = "Ocurrió un error durante la inserción del usuario: " + ex.Message;
                return View(user);
            }
        }



        [HttpGet]
        public ActionResult Login()
        {
            // Muestra la vista de inicio de sesión
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserDTO user)
        {

            UserDAO userDAO = new UserDAO();
            bool isValidCredentials = userDAO.ValidateUser(user.Email, user.Password);

            if (isValidCredentials)
            {

                // Obtenemos los detalles del usuario desde la base de datos
                UserDTO userDetails = userDAO.GetUserDetailsByEmail(user.Email);

                // Almacenamos los detalles del usuario en la sesión
                Session["UserId"] = userDetails.Id;
                Session["UserName"] = userDetails.Name;
                Session["UserLast_Name"] = userDetails.Last_Name;
                Session["UserRole"] = userDetails.Role_id;


                // Credenciales válidas, permite el acceso (por ejemplo, redirige a la página de inicio)
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Credenciales inválidas, muestra mensaje de error
                ViewBag.ErrorMessage = "Incorrect credentials, check the email and password";
            }


            // Si el modelo no es válido o las credenciales son inválidas, vuelve a mostrar la vista de inicio de sesión con los errores
            return View(user);
        }




        public ActionResult EditUser(int id)
        {
            try
            {
                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserById(id);
                if (user != null)
                {

                    List<DepartamentDTO> departaments = userRepository.ReadDepartament();
                    ViewBag.Departaments = new SelectList(departaments, "Id_departament", "Description");

                    // Si el usuario existe, muestra la vista de edición con los detalles del usuario
                    return View(user);
                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("ListUser");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("ListUser");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUser(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUser(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("ListUser");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error updating user: " + ex.Message);
                return View(user);
            }
        }




        public ActionResult EditUserSecurity(int id)
        {
            try
            {
                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserSecurityById(id);
                if (user != null)
                {

                    List<Roles> roles = userRepository.ReadRoles();
                    ViewBag.Roles = new SelectList(roles, "Id", "Description");
                    return View(user);
                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("ListUserSecurity");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("ListUserSecurity");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUserSecurity(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUserSecurity(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("ListUserSecurity");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error updating user: " + ex.Message);
                return View(user);
            }
        }

        public ActionResult EditUserSingle(int id)
        {
            try
            {


                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserSingleById(id);
                if (user != null)
                {

                    List<DepartamentDTO> departaments = userRepository.ReadDepartament();
                    ViewBag.Departaments = new SelectList(departaments, "Id_departament", "Description");

                    List<Roles> roles = userRepository.ReadRoles();
                    ViewBag.Roles = new SelectList(roles, "Id", "Description");
                    return View(user);


                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUserSingle(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUserSingle(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)

nomina2/Views/Payment/CreatePayment.cshtml
@model nomina2.Models.DTO.PaymentDTO

@{
    ViewBag.Title = "Create Payment";
    decimal amountSalary = ViewBag.AmountSalary ?? 0; // Asigna 0 si ViewBag.AmountSalary es nulo
    decimal department = ViewBag.Department_id ?? 0; // Asigna 0 si ViewBag.AmountSalary es nulo


}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Payment</title>
</head>
<body>
    <div>
        <h2>Create Payment</h2>

        <!-- Mostrar el mensaje de alerta genérico en caso de otro error -->
        @if (ViewBag.ErrorMessage != null)
        {
            <br />
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

        @using (Html.BeginForm("CreatePayment", "Payment", FormMethod.Post, new { @class = "form" }))
        {
            <!-- Nuevo TextBoxFor para mostrar el valor del userId -->
            <div class="form-group">
                <label>User ID:</label>
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.UserId })
            </div>

            <div class="form-group">
                <label>Amount Salary:</label>
                @Html.TextBoxFor(model => model.AmountSalary, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.AmountSalary })

            </div>

            <div class="form-group">
                <label>Date:</label>
                @Html.TextBoxFor(model => model.Date, new { @class = "form-control", type = "date", Value = DateTime.Now.ToString("yyyy-MM-dd") })
            </div>


            <div class="form-group">
                <label>Type:</label>


                @Html.DropDownListFor(model => model.Type, new SelectList(new[] { "J", "A" }), new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Worked days:</label>
                @if (department == 1)
                {
                    @Html.TextBoxFor(model => model.Worked_days, new { @class = "form-control", @readonly = "readonly" })
                }
                else
                {
                    @Html.TextBoxFor(model => model.Worked_days, new { @class = "form-control" })
                }
            </div>


            <div class="form-group">
                <label>Regular Hours:</label>
                @if (department != 1)
                {
                    @Html.TextBoxFor(model => model.Regular_Hours, new { @class = "form-control", @readonly = "readonly" })
                }
                else
                {
                    @Html.TextBoxFor(model => model.Regular_Hours, new { @class = "form-control" })
                }
            </div>
            <div class="form-group">
                <label>Overtime hours:</label>
                @if (department != 1)
                {
                    @Html.TextBoxFor(model => model.Overtime_hours, new { @class = "form-control", @readonly = "readonly" })
                }
                else
                {
                    @Html.TextBoxFor(model => model.Overtime_hours, new { @class = "form-control" })
                }
            </div>



            <div class="form-group">
                <label>Detail:</label>
                @Html.TextBoxFor(model => model.Detail, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Observation:</label>
                @Html.TextBoxFor(model => model.Observation, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        }
    </div>
</body>
</html>

nomina2/Views/Payment/DeletePayment.cshtml
@{
    ViewBag.Title = "Delete Payment";

}

<h2>Delete Payment</h2>

<p>Are you sure you want to delete this payment?</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



    <div class="form-actions">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Cancel", "ListPayment")
    </div>
}

nomina2/Views/Payment/EditPayment.cshtml
@model nomina2.Models.DTO.PaymentDTO

@{
    ViewBag.Title = "Edit Payment";
    decimal amountSalary = ViewBag.AmountSalary ?? 0; // Asigna 0 si ViewBag.AmountSalary es nulo
    decimal department = ViewBag.Department_id ?? 0; // Asigna 0 si ViewBag.AmountSalary es nulo

}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Payment</title>
</head>
<body>
    <div>
        <h2>Edit Payment</h2>

        <!-- Mostrar el mensaje de alerta genérico en caso de otro error -->
        @if (ViewBag.ErrorMessage != null)
        {
            <br />
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

        @using (Html.BeginForm("EditPayment", "Payment", FormMethod.Post, new { @class = "form" }))
        {
            @Html.HiddenFor(model => model.Id_payment) <!-- Agrega un campo oculto para el Id -->
            @Html.HiddenFor(model => model.Id_user) <!-- Agrega un campo oculto para el Id -->

            <div class="form-group">
                <label>Id payment:</label>
                @Html.DisplayFor(model => model.Id_payment) <!-- Mostrar el Id -->
            </div>

            <div class="form-group">
                <label>Id user:</label>
                @Html.DisplayFor(model => model.Id_user) <!-- Mostrar el Id -->
            </div>

            <div class="form-group">
                <label>Amount Salary:</label>
                @Html.EditorFor(model => model.AmountSalary, new { @class = "form-control", Value = ViewBag.AmountSalary })
            </div>

            <div class="form-group">
                <label>Date:</label>
                @Html.EditorFor(model => model.Date, new { @class = "form-control", type = "date" })
            </div>

            <div class="form-group">
                <label>Type:</label>
                @Html.EditorFor(model => model.Type, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Worked days:</label>
                @Html.EditorFor(model => model.Worked_days, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Regular Hours:</label>
                @Html.EditorFor(model => model.Regular_Hours, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Overtime hours:</label>
                @Html.EditorFor(model => model.Overtime_hours, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Gross Salary:</label>
                @Html.EditorFor(model => model.Gross_Salary, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Detail:</label>
                @Html.EditorFor(model => model.Detail, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Observation:</label>
                @Html.EditorFor(model => model.Observation, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save Changes</button>
        }
    </div>
</body>
</html>

nomina2/Views/Payment/ListPayment.cshtml
@model Tuple<List<nomina2.Models.DTO.PaymentDTO>, List<nomina2.Models.DTO.UserDTO>>


@{
    ViewBag.Title = "Payments";
    string searchKeywordValue = ViewBag.SearchKeyword ?? "";
    decimal amountSalary = Model.Item2.Count > 0 ? Model.Item2[0].Amount_salary : 0;
    decimal department = Model.Item2.Count > 0 ? Model.Item2[0].Department_id : 0;

    ViewBag.AmountSalary = amountSalary;
    ViewBag.Department_id = department;
}

<h2>Payments List</h2>

<div class="form-group" style="display: inline-flex;">
    <a href="@Url.Action("CreatePayment", "Payment", new { userId = ViewBag.SearchKeyword, amountSalary = ViewBag.AmountSalary, department = ViewBag.Department_id })" class="btn btn-success">CREATE</a>
    <a href="@Url.Action("ListUser","User")" class="btn btn-primary">List Users</a>
</div>
<br />
<br />
<form method="get" action="@Url.Action("ListPayment", "Payment")">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th>User ID</th>
                <th>Action</th>
                <th>Name</th>
                <th>NLast Name</th>
                <th>Amount Salary</th>
                <th>Departament</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td> <input type="text" class="form-control" name="searchKeyword" placeholder="Enter User ID" style="display: inline-flex; height: 35px; width: 250px; text-align: center; padding: 3px 5px; border: 1px solid #0a93f6; border-radius: 10px;" value="@searchKeywordValue"></td>
                <td> <button type="submit" class="btn btn-primary" style="display: inline-flex;">SEARCH</button></td>
                <td style="padding-right: 10px;">
                    @if (!string.IsNullOrWhiteSpace(ViewBag.SearchKeyword) && Model.Item2 != null && Model.Item2.Count > 0)
                    {
                        @Model.Item2[0].Name
                    }
                </td>

                <td style="">
                    @if (!string.IsNullOrWhiteSpace(ViewBag.SearchKeyword) && Model.Item2 != null && Model.Item2.Count > 0)
                    {
                        @Model.Item2[0].Last_Name
                    }
                </td>
                <td>
                    @if (!string.IsNullOrWhiteSpace(ViewBag.SearchKeyword) && Model.Item2 != null && Model.Item2.Count > 0)
                    {
                        @Model.Item2[0].Amount_salary.ToString("C", new System.Globalization.CultureInfo("es-CR"))
                    }
                </td>
                <td>
                    @if (!string.IsNullOrWhiteSpace(ViewBag.SearchKeyword) && Model.Item2 != null && Model.Item2.Count > 0)
                    {
                        @Model.Item2[0].Department_id
                    }
                </td>

            </tr>
        </tbody>
    </table>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>Id payment</th>
            <th>Id User</th>
            <th>Date</th>
            <th>Type</th>
            <th>Worked days</th>
            <th>Regular Hours</th>
            <th>Overtime hours</th>
            <th>Salary</th>
            <th>Gross Salary</th>
            <th>Details</th>
            <th>Observation</th>
            <th>Update date</th>
            <th>Update user</th>
            <th>Create date</th>
            <th>Create user</th>
            <th>Actions</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Item1.Count == 0)
        {
            <tr>
                <td colspan="17">No se encontraron registros</td>
            </tr>
        }
        else
        {
            foreach (var payment in Model.Item1)
            {
                <tr>
                    <td>@payment.Id_payment</td>
                    <td>@payment.Id_user</td>
                    <td>@payment.Date.ToString("dd/MM/yyyy")</td> <!-- Formato fecha -->
                    <td>@payment.Type</td>
                    <td>@payment.Worked_days</td>
                    <td>@payment.Regular_Hours</td>
                    <td>@payment.Overtime_hours</td>
                    <td>@payment.Salary.ToString("C", new System.Globalization.CultureInfo("es-CR"))</td>
                    <td>@payment.Gross_Salary.ToString("C", new System.Globalization.CultureInfo("es-CR"))</td>
                    <td>@payment.Detail</td>
                    <td>@payment.Observation</td>
                    <td>@payment.Update_date</td>
                    <td>@payment.Update_user</td>
                    <td>@payment.Create_date</td>
                    <td>@payment.Create_user</td>
                    <td>
                        <a href="@Url.Action("EditPayment", "Payment", new { id = payment.Id_payment, userId = ViewBag.SearchKeyword, amountSalary = ViewBag.AmountSalary, department = ViewBag.Department_id })" class="btn btn-success">EDIT</a>
                    </td>
                    <td>
                        <a href="@Url.Action("DeletePayment", "Payment", new { id = payment.Id_payment, userId = ViewBag.SearchKeyword  })" class="btn btn-danger">DEL</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>