nomina2/Controllers/OvertimeController.cs
using nomina2.Models.DAO;
using nomina2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace nomina2.Controllers
{
    public class OvertimeController : Controller
    {
        private OvertimeDAO overtimeRepository = new OvertimeDAO();    


        public ActionResult ListOvertime(int id)
        {
            // Obtener la lista de overtime filtrada por el ID de usuario
            List<OvertimeDTO> userOvertimes = overtimeRepository.ReadActiveOvertimeByUserId(id);

            // Pasar la lista filtrada a la vista

            ViewBag.UserId = id;
            return View(userOvertimes);
        }

        public ActionResult CreateOvertime(int userId)
        {
            ViewBag.UserId = userId; // Pasar el ID de usuario a la vista

            return View();
        }



        // POST: User/Create
        [HttpPost]
        public ActionResult CreateOvertime(OvertimeDTO overtime)
        {
            try
            {
                string result = overtimeRepository.InsertOvertime(overtime);

                if (result == "Success")
                {
                    int Id_actual = overtime.Id;

                    // Crear una instancia de RouteValueDictionary para mantener los parámetros de filtro
                    var routeValues = new RouteValueDictionary(new { id = Id_actual });

                    // Redireccionar a la vista "ListOvertime" en caso de éxito
                    return RedirectToAction("ListOvertime", routeValues);
                }
                else
                {
                    // Si la inserción falla, agregar un mensaje de alerta a la ViewBag
                    ViewBag.ErrorMessage = "Error al insertar el overtime en la base de datos.";
                }
            }
            catch (Exception ex)
            {
                // En caso de excepción, agregar un mensaje de alerta a la ViewBag
                ViewBag.ErrorMessage = "Ocurrió un error durante la inserción del overtime: " + ex.Message;
            }

            // Devolver la vista "CreateOvertime" con los datos del overtime ingresados previamente y el mensaje de alerta (si corresponde).
            return View(overtime);
        }

        public ActionResult DeleteOvertime(int id)
        {
            bool success = overtimeRepository.SoftDeleteOvertime(id);
            if (success)
            {
                return RedirectToAction("ListOvertime", new { id = id });
            }
            else
            {
                ViewBag.ErrorMessage = "Error al eliminar el registro.";
                return View("ListOvertime", overtimeRepository.ReadActiveOvertimeByUserId(id));
            }
        }

        



    }
}

nomina2/Controllers/UserController.cs
using nomina2.Models;
using nomina2.Models.DAO;
using nomina2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nomina2.Controllers
{
    public class UserController : Controller
    {
        private UserDAO userRepository = new UserDAO();
        private readonly OvertimeDAO overtimeRepository = new OvertimeDAO();
        private readonly DeductionDAO deductionRepository = new DeductionDAO();
        //private readonly LicenseDAO licenseRepository = new LicenseDAO();

        // GET: User
        public ActionResult ListUser(string searchKeyword)
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadUsers(searchKeyword));
        }

        public ActionResult ListUserSecurity(string searchKeyword)
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadUsers(searchKeyword));
        }




        public ActionResult RolesList()
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadRoles());
        }

        public ActionResult ListDepartament()
        {
            // Devuelve la vista Index con la lista de usuarios
            return View(userRepository.ReadDepartament());
        }

        public ActionResult CreateUser()
        {
            // Obtener los roles disponibles
            var roles = userRepository.ReadRoles().ToList();
            var departaments = userRepository.ReadDepartament().ToList();
            ViewBag.Roles = new SelectList(roles, "id", "Description");
            ViewBag.Departaments = new SelectList(departaments, "id_departament", "Description");

            return View();
        }


        [HttpPost]
        public ActionResult CreateUser(UserDTO user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (user.Password == user.ConfirmPassword)
                    {
                        string result = userRepository.InsertUser(user);

                        if (result == "Success")
                        {
                            // Redireccionar a la vista "Index" en caso de éxito
                            return RedirectToAction("Login");
                        }
                        else
                        {
                            // Si la inserción falla, agregar un mensaje de alerta a la ViewBag
                            ViewBag.ErrorMessage = "Error al insertar el usuario en la base de datos.";
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("ConfirmPassword", "Passwords do not match");
                    }
                }

                // Si la validación falla, recuperar las listas de roles y departamentos
                var roles = userRepository.ReadRoles().ToList();
                var departaments = userRepository.ReadDepartament().ToList();
                ViewBag.Roles = new SelectList(roles, "id", "Description");
                ViewBag.Departaments = new SelectList(departaments, "id_departament", "Description");

                return View(user);
            }
            catch (Exception ex)
            {
                // En caso de excepción, agregar un mensaje de alerta a la ViewBag
                ViewBag.ErrorMessage = "Ocurrió un error durante la inserción del usuario: " + ex.Message;
                return View(user);
            }
        }



        [HttpGet]
        public ActionResult Login()
        {
            // Muestra la vista de inicio de sesión
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserDTO user)
        {

            UserDAO userDAO = new UserDAO();
            bool isValidCredentials = userDAO.ValidateUser(user.Email, user.Password);

            if (isValidCredentials)
            {

                // Obtenemos los detalles del usuario desde la base de datos
                UserDTO userDetails = userDAO.GetUserDetailsByEmail(user.Email);

                // Almacenamos los detalles del usuario en la sesión
                Session["UserId"] = userDetails.Id;
                Session["UserName"] = userDetails.Name;
                Session["UserLast_Name"] = userDetails.Last_Name;
                Session["UserRole"] = userDetails.Role_id;


                // Credenciales válidas, permite el acceso (por ejemplo, redirige a la página de inicio)
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Credenciales inválidas, muestra mensaje de error
                ViewBag.ErrorMessage = "Incorrect credentials, check the email and password";
            }


            // Si el modelo no es válido o las credenciales son inválidas, vuelve a mostrar la vista de inicio de sesión con los errores
            return View(user);
        }




        public ActionResult EditUser(int id)
        {
            try
            {
                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserById(id);
                if (user != null)
                {

                    List<DepartamentDTO> departaments = userRepository.ReadDepartament();
                    ViewBag.Departaments = new SelectList(departaments, "Id_departament", "Description");

                    // Si el usuario existe, muestra la vista de edición con los detalles del usuario
                    return View(user);
                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("ListUser");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("ListUser");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUser(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUser(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("ListUser");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error updating user: " + ex.Message);
                return View(user);
            }
        }




        public ActionResult EditUserSecurity(int id)
        {
            try
            {
                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserSecurityById(id);
                if (user != null)
                {

                    List<Roles> roles = userRepository.ReadRoles();
                    ViewBag.Roles = new SelectList(roles, "Id", "Description");
                    return View(user);
                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("ListUserSecurity");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("ListUserSecurity");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUserSecurity(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUserSecurity(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("ListUserSecurity");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error updating user: " + ex.Message);
                return View(user);
            }
        }

        public ActionResult EditUserSingle(int id)
        {
            try
            {


                // Intenta obtener un usuario específico utilizando el método GetUserById del repositorio UserDAO
                UserDTO user = userRepository.GetUserSingleById(id);
                if (user != null)
                {

                    List<DepartamentDTO> departaments = userRepository.ReadDepartament();
                    ViewBag.Departaments = new SelectList(departaments, "Id_departament", "Description");

                    List<Roles> roles = userRepository.ReadRoles();
                    ViewBag.Roles = new SelectList(roles, "Id", "Description");
                    return View(user);


                }
                else
                {
                    Console.WriteLine("User not found");
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error getting user: " + ex.Message);
                return RedirectToAction("Index", "Home");
            }
        }


        // POST: User/Edit/
        [HttpPost]
        public ActionResult EditUserSingle(UserDTO user)
        {
            try
            {
                // Intenta actualizar los detalles del usuario utilizando el método UpdateUser del repositorio UserDAO
                string result = userRepository.UpdateUserSingle(user);
                Console.WriteLine("User updated: " + result);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)

nomina2/Views/Overtime/CreateOvertime.cshtml
@model nomina2.Models.DTO.OvertimeDTO

@{
    ViewBag.Title = "Create Overtime";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Overtime</title>
</head>
<body>
    <div>
        <h2>Create Overtime</h2>

        <!-- Mostrar el mensaje de alerta genérico en caso de otro error -->
        @if (ViewBag.ErrorMessage != null)
        {
            <br />
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

        @using (Html.BeginForm("CreateOvertime", "Overtime", FormMethod.Post, new { @class = "form" }))
        {
            <!-- Nuevo TextBoxFor para mostrar el valor del userId -->
            <div class="form-group">
                <label>User ID:</label>
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.UserId })
            </div>

            <div class="form-group">
                <label>Description:</label>
                @Html.TextBoxFor(model => model.Overtime_description, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Type Action:</label>
                @Html.TextBoxFor(model => model.Type_action, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Value:</label>
                @Html.TextBoxFor(model => model.Overtime_value, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        }
    </div>
</body>
</html>

nomina2/Views/Overtime/DeleteOvertime.cshtml
@model nomina2.Models.DTO.OvertimeDTO

@{
    ViewBag.Title = "Delete Overtime";

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

    <h2>Delete User</h2>

    <p>Are you sure you want to delete the record??</p>

    <table class="table">
        <thead>
            <tr>
                <th>Overtime_id</th>
                <th>Id</th>
                <th>Type_action</th>
            </tr>
            <tr>
                <td>@Model.Overtime_id</td>
                <td>@Model.Id</td>                
                <td>@Model.Type_action</td>
            </tr>
        </thead>
    </table>

    @using (Html.BeginForm("DeleteOvertime", "Overtime", new { id = Model.Overtime_id }, FormMethod.Post, new { id = "deleteForm" }))
    {
        @Html.AntiForgeryToken()

        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Cancel", "ListOvertime", null, new { @class = "btn btn-default" })
    }

    @section Scripts {
        <script>
            $(document).ready(function () {
                $('#deleteForm').submit(function () {
                    return confirm("Are you sure you want to delete the record?");
                });
            });
        </script>
    }
</body>
</html>

nomina2/Views/Overtime/ListOvertime.cshtml
@model List<nomina2.Models.DTO.OvertimeDTO>

@{
    ViewBag.Title = "Overtime List";
}

<h2>Overtime List for User with ID: @ViewBag.UserId</h2>

<a href="@Url.Action("CreateOvertime", "Overtime", new { userId = ViewBag.UserId })" class="btn btn-success">Create</a>
<a href="@Url.Action("RolesList","User")" class="btn btn-primary">Roles Usuario </a>
<br />
<table class="table">
    <thead>
        <tr>
            <th>ID Overtime</th>
            <th>ID</th>
            <th>Type Action</th>
            <th>Descripcion</th>
            <th>Value</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var overtime in Model)
        {
            <tr>
                <td>@overtime.Overtime_id</td>
                <td>@overtime.Id</td>
                <td>@overtime.Overtime_description</td>
                <td>@overtime.Type_action</td>
                <td>@overtime.Overtime_value</td>
                <td>
                    <a href="@Url.Action("Edit", "Overtime", new { id = overtime.Id })" class="btn btn-success">Edit</a>
                    <a href="@Url.Action("DeleteOvertime", "Overtime", new { id = overtime.Overtime_id })" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

nomina2/Views/Overtime/UpdateOvertime.cshtml
@model nomina2.Models.DTO.OvertimeDTO

@{
    ViewBag.Title = "UpdateOvertime";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update Overtime</title>
</head>
<body>
    <div>
        <h2>Update Deduction</h2>

        <!-- Mostrar el mensaje de alerta genérico en caso de otro error -->
        @if (ViewBag.ErrorMessage != null)
        {
            <br />
            <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
        }

        @using (Html.BeginForm("UpdateOvertime", "Overtime", FormMethod.Post, new { @class = "form" }))
        {
            <!-- Nuevo TextBoxFor para mostrar el valor del userId -->
            <div class="form-group">
                <label>User ID:</label>
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.UserId })
            </div>

            <div class="form-group">
                <label>Description:</label>
                @Html.TextBoxFor(model => model.Overtime_description, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Type Action:</label>
                @Html.TextBoxFor(model => model.Type_action, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label>Value:</label>
                @Html.TextBoxFor(model => model.Overtime_value, new { @class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        }
    </div>
</body>
</html>